# Scene library. Every scene is composed from the pictogram primitives already
# in the mockup (hex, tile, token, card, arrow, hand, lock, bag, trophy, check,
# cross, pair, map) plus a handful of new primitives listed at the bottom.
# `desc` is the composition Claude Code draws, in a 100x100 box, gold = the
# thing the player does, ivory = the world.
SCENES = {
  # --- HOOK: what kind of game this is ---
  "hexes-tokens":   "three touching hex tiles, animal tokens on two",
  "hexes-dice":     "hex tiles with a die beside them",
  "cards-hand":     "a fan of five cards",
  "cards-tableau":  "cards laid in a row in front of a player marker",
  "deck-cards":     "a face-down deck with two cards drawn beside it",
  "dice-cup":       "a cup with three dice spilling out",
  "map-armies":     "a map of four regions with meeples in three",
  "map-board":      "a board with routes/regions and a few pieces",
  "workers-board":  "a board with action spots, meeples on two",
  "hidden-role":    "a face-down card with a question mark",
  "team-vs-team":   "two clusters of meeples facing each other",
  "coop-threat":    "a cluster of meeples with a shield facing a skull",
  "drawing-pad":    "a pencil over a sketch pad",
  "word-bubble":    "a speech bubble with three lines",
  "route-network":  "dots connected by lines, one line highlighted",
  "coins-stack":    "a stack of coins with a banknote",
  "stock-chart":    "a rising line chart with a coin on it",
  "grid-pieces":    "a grid with a few abstract pieces",
  "duel":           "two figures facing each other over a card",
  "timer-sand":     "an hourglass with cards",
  "flick":          "a finger flicking a disc",
  "city-blocks":    "three buildings of different heights",
  "farm-fields":    "a field grid with a barn and a sheep",
  "engine-gears":   "two meshing gears with an arrow looping",
  "auction-gavel":  "a gavel over a card with rising coin stacks",
  "handshake":      "two hands shaking over cards",
  "push-luck":      "a die showing a skull and a die showing a gem",
  "race-track":     "a track with three pieces at different distances",
  "polyomino":      "tetris-like pieces fitting into a grid",
  "question-cards": "a card with a question mark, a hand raised",
  "magnifier":      "a magnifying glass over cards",
  "spaceship":      "a rocket over a planet",
  "castle-siege":   "a castle with pieces attacking",
  "story-picture":  "a picture card with a speech bubble",
  "trains":         "a train on a track between two cities",
  "ship-sea":       "a boat on waves with cargo",
  "monster-fight":  "a hero figure facing a monster",
  "campaign-book":  "an open book with a map",
  "pencil-sheet":   "a pencil over a scoring sheet grid",
  "stack-tower":    "pieces stacked in a wobbly tower",
  "fish-hook":      "a fishing line with a fish",
  "phone":          "a phone with an app grid",
  "vote-hands":     "raised hands with a ballot",
  # --- WIN ---
  "trophy-points":  "trophy with point chips beneath",
  "trophy-first":   "trophy with a finish flag: first to reach wins",
  "trophy-team":    "trophy shared by a group of meeples",
  "trophy-standing":"trophy with one figure standing, others crossed out",
  "trophy-coins":   "trophy with a coin stack: richest wins",
  "trophy-survive": "trophy with a shield and a check: beat the game together",
  "trophy-guess":   "trophy with a check on a card: guess right",
  "trophy-area":    "trophy over a map with most regions shaded",
  "trophy-rounds":  "trophy with tally marks: most round wins",
  "trophy-lowest":  "trophy with a small number: fewest points wins",
  # --- TURN (strip frames) ---
  "draw-card":      "hand drawing a card from a deck",
  "play-card":      "hand placing a card face-up on the table",
  "pick-market":    "row of four cards, one highlighted, hand pointing",
  "place-worker":   "meeple being placed on a board spot",
  "roll-dice":      "two dice mid-roll",
  "place-tile":     "tile snapping onto a map",
  "place-token":    "token dropping onto a tile",
  "pick-pair":      "column of tile+token pairs, one highlighted",
  "bid-coins":      "hand pushing coins forward",
  "move-piece":     "piece moving along an arrow",
  "trade-cards":    "two hands swapping cards",
  "collect-goods":  "resources flowing into a hand",
  "build":          "a building being placed with a plus",
  "attack":         "two pieces with a clash burst",
  "flip-card":      "card mid-flip",
  "discuss":        "two speech bubbles",
  "speak-clue":     "one speech bubble with a single word",
  "guess":          "hand pointing at one of three cards",
  "draw-sketch":    "pencil drawing on a card",
  "write":          "pencil writing on a sheet",
  "vote":           "hands raised, one card chosen",
  "reveal":         "hand turning a hidden card face-up",
  "flick-piece":    "finger flicking a disc",
  "stack-piece":    "hand placing a piece on a stack",
  "pass-turn":      "arrow curving to the next seat",
  "pick-die":       "hand taking one die from a pool",
  "score-round":    "tally marks with a check",
  "take-or-pay":    "card with a coin and a fork arrow",
  "explore":        "a figure with a compass on a map",
  "answer":         "hand writing a number on a slate",
  "listen":         "an ear with sound lines",
  "act":            "a figure mid-gesture with a spotlight",
  "count-sync":     "three hands each holding a card, no speech bubble",
  # --- WATCH OUT ---
  "lock":           "tile with token and a lock: permanent",
  "alert":          "warning triangle beside a card",
  "no-talk":        "speech bubble crossed out",
  "hidden":         "an eye crossed out over a card",
  "bust":           "die showing a skull, coins vanishing",
  "timer":          "hourglass nearly empty",
  "one-only":       "a hand holding a single card, a second card crossed out",
  "must":           "an exclamation over an action arrow",
  "order":          "three numbered dots in a strict sequence",
  "count":          "cards with a number badge",
  # --- TURN ONE ---
  "hand-pair":      "hand pointing at a highlighted pair with a check",
  "hand-card":      "hand pointing at a highlighted card with a check",
  "hand-worker":    "hand placing a meeple on the obvious spot",
  "hand-cheap":     "hand pointing at the cheapest item in a row",
  "hand-center":    "hand pointing at the middle of a map",
  "hand-talk":      "hand beside a speech bubble: just say something",
  "hand-watch":     "an eye watching the other players",
  "hand-safe":      "hand pointing at a shield-marked option",
}
# New primitives implied above, beyond the mockup's set:
# die, meeple, coin, banknote, gavel, shield, skull, pencil, sheet, bubble,
# hourglass, eye, magnifier, gear, building, flag, tally, compass.
